name: animalspredictor
description: Clasificador de animales con colección personal.
publish_to: 'none'
version: 2.0.0+6

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.8.0
  firebase_auth: ^6.5.7
  firebase_core: ^4.13.0
  image_picker: ^1.2.3
  permission_handler: ^13.0.1
  shared_preferences: ^2.5.3
  audioplayers: ^6.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/arana.jpg
    - assets/ardilla.jpg
    - assets/caballo.jpg
    - assets/elefante.jpg
    - assets/farm_animals.png
    - assets/gallina.jpg
    - assets/gato.jpg
    - assets/mariposa.jpg
    - assets/oveja.jpg
    - assets/perro.jpg
    - assets/vaca.jpg
    - assets/models/
    - assets/sonidos/
    - assets/sonidos/animales/
  fonts:
    - family: Andika
      fonts:
        - asset: assets/fonts/Andika-Regular.ttf
          weight: 400
        - asset: assets/fonts/Andika-Bold.ttf
          weight: 700
