// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Zy6H3pUNle88N2nD54cT_2bctG6bhC4',
    appId: '1:211987682756:web:82e819f0c8063ce8304091',
    messagingSenderId: '211987682756',
    projectId: 'tfm-project-6f488',
    authDomain: 'tfm-project-6f488.firebaseapp.com',
    storageBucket: 'tfm-project-6f488.appspot.com',
    measurementId: 'G-FS7ZPYTEDZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDenHXVWY1TiuNyY-ohsuA553Z4ofCgX4E',
    appId: '1:211987682756:android:d6d5da1d37b70993304091',
    messagingSenderId: '211987682756',
    projectId: 'tfm-project-6f488',
    storageBucket: 'tfm-project-6f488.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdukneSS2MO5OQDHXXLFa_XcDRIHDyPic',
    appId: '1:211987682756:ios:a0369d6f784a3236304091',
    messagingSenderId: '211987682756',
    projectId: 'tfm-project-6f488',
    storageBucket: 'tfm-project-6f488.appspot.com',
    androidClientId:
        '211987682756-4rkildar8jhf0cf87f4a57i09erjvkdq.apps.googleusercontent.com',
    iosClientId:
        '211987682756-vmava2dcd6661rep6dapr6otjj93nk2f.apps.googleusercontent.com',
    iosBundleId: 'com.tfm.animalspredictor',
  );
}
